# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aawin2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_aawin2(object):
    def setupUi(self, aawin2):
        aawin2.setObjectName("aawin2")
        aawin2.setEnabled(True)
        aawin2.resize(720, 480)
        aawin2.setMinimumSize(QtCore.QSize(720, 480))
        aawin2.setMaximumSize(QtCore.QSize(720, 480))
        aawin2.setStyleSheet("background-color:rgb(241,222,255);")
        self.label = QtWidgets.QLabel(aawin2)
        self.label.setGeometry(QtCore.QRect(50, 10, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(aawin2)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(aawin2)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(aawin2)
        self.label_4.setGeometry(QtCore.QRect(40, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(aawin2)
        self.label_5.setGeometry(QtCore.QRect(40, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(aawin2)
        self.label_6.setGeometry(QtCore.QRect(40, 430, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(aawin2)
        self.label_7.setGeometry(QtCore.QRect(110, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(aawin2)
        self.label_8.setGeometry(QtCore.QRect(180, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(aawin2)
        self.label_9.setGeometry(QtCore.QRect(250, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(aawin2)
        self.label_10.setGeometry(QtCore.QRect(320, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(aawin2)
        self.label_11.setGeometry(QtCore.QRect(390, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(aawin2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(100, 160, 41, 20))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.a1a2 = QtWidgets.QLineEdit(aawin2)
        self.a1a2.setEnabled(True)
        self.a1a2.setGeometry(QtCore.QRect(170, 160, 41, 20))
        self.a1a2.setAlignment(QtCore.Qt.AlignCenter)
        self.a1a2.setObjectName("a1a2")
        self.a1a3 = QtWidgets.QLineEdit(aawin2)
        self.a1a3.setEnabled(True)
        self.a1a3.setGeometry(QtCore.QRect(240, 160, 41, 20))
        self.a1a3.setAlignment(QtCore.Qt.AlignCenter)
        self.a1a3.setObjectName("a1a3")
        self.a1a4 = QtWidgets.QLineEdit(aawin2)
        self.a1a4.setEnabled(True)
        self.a1a4.setGeometry(QtCore.QRect(310, 160, 41, 20))
        self.a1a4.setAlignment(QtCore.Qt.AlignCenter)
        self.a1a4.setObjectName("a1a4")
        self.a1a5 = QtWidgets.QLineEdit(aawin2)
        self.a1a5.setEnabled(True)
        self.a1a5.setGeometry(QtCore.QRect(380, 160, 41, 20))
        self.a1a5.setAlignment(QtCore.Qt.AlignCenter)
        self.a1a5.setObjectName("a1a5")
        self.lineEdit_6 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 230, 41, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 230, 41, 20))
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.a2a3 = QtWidgets.QLineEdit(aawin2)
        self.a2a3.setEnabled(True)
        self.a2a3.setGeometry(QtCore.QRect(240, 230, 41, 20))
        self.a2a3.setAlignment(QtCore.Qt.AlignCenter)
        self.a2a3.setObjectName("a2a3")
        self.a2a4 = QtWidgets.QLineEdit(aawin2)
        self.a2a4.setEnabled(True)
        self.a2a4.setGeometry(QtCore.QRect(310, 230, 41, 20))
        self.a2a4.setAlignment(QtCore.Qt.AlignCenter)
        self.a2a4.setObjectName("a2a4")
        self.a2a5 = QtWidgets.QLineEdit(aawin2)
        self.a2a5.setEnabled(True)
        self.a2a5.setGeometry(QtCore.QRect(380, 230, 41, 20))
        self.a2a5.setAlignment(QtCore.Qt.AlignCenter)
        self.a2a5.setObjectName("a2a5")
        self.lineEdit_11 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setGeometry(QtCore.QRect(100, 300, 41, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setGeometry(QtCore.QRect(170, 300, 41, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setGeometry(QtCore.QRect(240, 300, 41, 20))
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.a3a4 = QtWidgets.QLineEdit(aawin2)
        self.a3a4.setEnabled(True)
        self.a3a4.setGeometry(QtCore.QRect(310, 300, 41, 20))
        self.a3a4.setAlignment(QtCore.Qt.AlignCenter)
        self.a3a4.setObjectName("a3a4")
        self.a3a5 = QtWidgets.QLineEdit(aawin2)
        self.a3a5.setEnabled(True)
        self.a3a5.setGeometry(QtCore.QRect(380, 300, 41, 20))
        self.a3a5.setAlignment(QtCore.Qt.AlignCenter)
        self.a3a5.setObjectName("a3a5")
        self.lineEdit_16 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setGeometry(QtCore.QRect(100, 370, 41, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_17.setEnabled(False)
        self.lineEdit_17.setGeometry(QtCore.QRect(170, 370, 41, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_18.setEnabled(False)
        self.lineEdit_18.setGeometry(QtCore.QRect(240, 370, 41, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setGeometry(QtCore.QRect(310, 370, 41, 21))
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.a4a5 = QtWidgets.QLineEdit(aawin2)
        self.a4a5.setEnabled(True)
        self.a4a5.setGeometry(QtCore.QRect(380, 370, 41, 20))
        self.a4a5.setAlignment(QtCore.Qt.AlignCenter)
        self.a4a5.setObjectName("a4a5")
        self.lineEdit_21 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_21.setEnabled(False)
        self.lineEdit_21.setGeometry(QtCore.QRect(100, 430, 41, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_22.setEnabled(False)
        self.lineEdit_22.setGeometry(QtCore.QRect(170, 430, 41, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_23.setEnabled(False)
        self.lineEdit_23.setGeometry(QtCore.QRect(240, 430, 41, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_24.setEnabled(False)
        self.lineEdit_24.setGeometry(QtCore.QRect(310, 430, 41, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(aawin2)
        self.lineEdit_25.setEnabled(False)
        self.lineEdit_25.setGeometry(QtCore.QRect(380, 430, 41, 20))
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.back = QtWidgets.QPushButton(aawin2)
        self.back.setGeometry(QtCore.QRect(510, 180, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.next = QtWidgets.QPushButton(aawin2)
        self.next.setGeometry(QtCore.QRect(510, 310, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.next.setFont(font)
        self.next.setObjectName("next")

        self.retranslateUi(aawin2)
        QtCore.QMetaObject.connectSlotsByName(aawin2)

    def retranslateUi(self, aawin2):
        _translate = QtCore.QCoreApplication.translate
        aawin2.setWindowTitle(_translate("aawin2", "Розрахунок.Альтернативи за К2"))
        self.label.setText(_translate("aawin2", "Матриця попарних порівнянь Альтернатив за Критерієм 2"))
        self.label_2.setText(_translate("aawin2", "А1"))
        self.label_3.setText(_translate("aawin2", "А2"))
        self.label_4.setText(_translate("aawin2", "А3"))
        self.label_5.setText(_translate("aawin2", "А4"))
        self.label_6.setText(_translate("aawin2", "А5"))
        self.label_7.setText(_translate("aawin2", "А1"))
        self.label_8.setText(_translate("aawin2", "А2"))
        self.label_9.setText(_translate("aawin2", "А3"))
        self.label_10.setText(_translate("aawin2", "А4"))
        self.label_11.setText(_translate("aawin2", "А5"))
        self.lineEdit.setText(_translate("aawin2", "1"))
        self.lineEdit_7.setText(_translate("aawin2", "1"))
        self.lineEdit_13.setText(_translate("aawin2", "1"))
        self.lineEdit_19.setText(_translate("aawin2", "1"))
        self.lineEdit_25.setText(_translate("aawin2", "1"))
        self.back.setText(_translate("aawin2", "Назад"))
        self.next.setText(_translate("aawin2", "Далі"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aawin2 = QtWidgets.QDialog()
    ui = Ui_aawin2()
    ui.setupUi(aawin2)
    aawin2.show()
    sys.exit(app.exec_())

