# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fin1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fin1(object):
    def setupUi(self, fin1):
        fin1.setObjectName("fin1")
        fin1.setEnabled(True)
        fin1.resize(720, 380)
        fin1.setMinimumSize(QtCore.QSize(720, 380))
        fin1.setMaximumSize(QtCore.QSize(720, 380))
        fin1.setStyleSheet("background-color:rgb(241,222,255);")
        self.label = QtWidgets.QLabel(fin1)
        self.label.setGeometry(QtCore.QRect(140, 10, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(fin1)
        self.label_2.setGeometry(QtCore.QRect(230, 130, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(fin1)
        self.label_7.setGeometry(QtCore.QRect(260, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.a1 = QtWidgets.QLineEdit(fin1)
        self.a1.setEnabled(False)
        self.a1.setGeometry(QtCore.QRect(280, 130, 121, 20))
        self.a1.setText("")
        self.a1.setAlignment(QtCore.Qt.AlignCenter)
        self.a1.setObjectName("a1")
        self.tomenu = QtWidgets.QPushButton(fin1)
        self.tomenu.setGeometry(QtCore.QRect(560, 260, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tomenu.setFont(font)
        self.tomenu.setObjectName("tomenu")
        self.label_3 = QtWidgets.QLabel(fin1)
        self.label_3.setGeometry(QtCore.QRect(230, 170, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(fin1)
        self.label_4.setGeometry(QtCore.QRect(230, 210, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(fin1)
        self.label_5.setGeometry(QtCore.QRect(230, 250, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(fin1)
        self.label_6.setGeometry(QtCore.QRect(230, 290, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.a2 = QtWidgets.QLineEdit(fin1)
        self.a2.setEnabled(False)
        self.a2.setGeometry(QtCore.QRect(280, 170, 121, 20))
        self.a2.setText("")
        self.a2.setAlignment(QtCore.Qt.AlignCenter)
        self.a2.setObjectName("a2")
        self.a3 = QtWidgets.QLineEdit(fin1)
        self.a3.setEnabled(False)
        self.a3.setGeometry(QtCore.QRect(280, 210, 121, 20))
        self.a3.setText("")
        self.a3.setAlignment(QtCore.Qt.AlignCenter)
        self.a3.setObjectName("a3")
        self.a4 = QtWidgets.QLineEdit(fin1)
        self.a4.setEnabled(False)
        self.a4.setGeometry(QtCore.QRect(280, 250, 121, 20))
        self.a4.setText("")
        self.a4.setAlignment(QtCore.Qt.AlignCenter)
        self.a4.setObjectName("a4")
        self.a5 = QtWidgets.QLineEdit(fin1)
        self.a5.setEnabled(False)
        self.a5.setGeometry(QtCore.QRect(280, 290, 121, 20))
        self.a5.setText("")
        self.a5.setAlignment(QtCore.Qt.AlignCenter)
        self.a5.setObjectName("a5")
        self.label_11 = QtWidgets.QLabel(fin1)
        self.label_11.setGeometry(QtCore.QRect(30, 330, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.calc = QtWidgets.QPushButton(fin1)
        self.calc.setGeometry(QtCore.QRect(560, 190, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calc.setFont(font)
        self.calc.setObjectName("calc")
        self.back = QtWidgets.QPushButton(fin1)
        self.back.setGeometry(QtCore.QRect(560, 120, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back.setFont(font)
        self.back.setObjectName("back")

        self.retranslateUi(fin1)
        QtCore.QMetaObject.connectSlotsByName(fin1)

    def retranslateUi(self, fin1):
        _translate = QtCore.QCoreApplication.translate
        fin1.setWindowTitle(_translate("fin1", "Розрахунок1.Результат"))
        self.label.setText(_translate("fin1", "Результат. Таблиця глобальних пріоритетів"))
        self.label_2.setText(_translate("fin1", "А1"))
        self.label_7.setText(_translate("fin1", "Глобальний пріоритет"))
        self.tomenu.setText(_translate("fin1", "В меню"))
        self.label_3.setText(_translate("fin1", "А2"))
        self.label_4.setText(_translate("fin1", "А3"))
        self.label_5.setText(_translate("fin1", "А4"))
        self.label_6.setText(_translate("fin1", "А5"))
        self.label_11.setText(_translate("fin1", "*Найкращим вибором є Альтернатива з найбільшим за величиною Глобальним Пріоритетом"))
        self.calc.setText(_translate("fin1", "Обчислити"))
        self.back.setText(_translate("fin1", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fin1 = QtWidgets.QDialog()
    ui = Ui_fin1()
    ui.setupUi(fin1)
    fin1.show()
    sys.exit(app.exec_())

