# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fin3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fin3(object):
    def setupUi(self, fin3):
        fin3.setObjectName("fin3")
        fin3.setEnabled(True)
        fin3.resize(720, 380)
        fin3.setMinimumSize(QtCore.QSize(720, 380))
        fin3.setMaximumSize(QtCore.QSize(720, 380))
        fin3.setStyleSheet("background-color:rgb(241,222,255);")
        self.label = QtWidgets.QLabel(fin3)
        self.label.setGeometry(QtCore.QRect(30, 10, 641, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(fin3)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tm = QtWidgets.QLineEdit(fin3)
        self.tm.setEnabled(False)
        self.tm.setGeometry(QtCore.QRect(220, 80, 121, 20))
        self.tm.setText("")
        self.tm.setAlignment(QtCore.Qt.AlignCenter)
        self.tm.setObjectName("tm")
        self.tomenu = QtWidgets.QPushButton(fin3)
        self.tomenu.setGeometry(QtCore.QRect(560, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tomenu.setFont(font)
        self.tomenu.setObjectName("tomenu")
        self.label_8 = QtWidgets.QLabel(fin3)
        self.label_8.setGeometry(QtCore.QRect(190, 120, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(fin3)
        self.label_9.setGeometry(QtCore.QRect(190, 160, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(fin3)
        self.label_10.setGeometry(QtCore.QRect(190, 200, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(fin3)
        self.label_11.setGeometry(QtCore.QRect(190, 240, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(fin3)
        self.label_12.setGeometry(QtCore.QRect(190, 280, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.s1 = QtWidgets.QLineEdit(fin3)
        self.s1.setEnabled(False)
        self.s1.setGeometry(QtCore.QRect(410, 120, 121, 20))
        self.s1.setText("")
        self.s1.setAlignment(QtCore.Qt.AlignCenter)
        self.s1.setObjectName("s1")
        self.s2 = QtWidgets.QLineEdit(fin3)
        self.s2.setEnabled(False)
        self.s2.setGeometry(QtCore.QRect(410, 160, 121, 20))
        self.s2.setText("")
        self.s2.setAlignment(QtCore.Qt.AlignCenter)
        self.s2.setObjectName("s2")
        self.s3 = QtWidgets.QLineEdit(fin3)
        self.s3.setEnabled(False)
        self.s3.setGeometry(QtCore.QRect(410, 200, 121, 20))
        self.s3.setText("")
        self.s3.setAlignment(QtCore.Qt.AlignCenter)
        self.s3.setObjectName("s3")
        self.s4 = QtWidgets.QLineEdit(fin3)
        self.s4.setEnabled(False)
        self.s4.setGeometry(QtCore.QRect(410, 240, 121, 20))
        self.s4.setText("")
        self.s4.setAlignment(QtCore.Qt.AlignCenter)
        self.s4.setObjectName("s4")
        self.s5 = QtWidgets.QLineEdit(fin3)
        self.s5.setEnabled(False)
        self.s5.setGeometry(QtCore.QRect(410, 280, 121, 20))
        self.s5.setText("")
        self.s5.setAlignment(QtCore.Qt.AlignCenter)
        self.s5.setObjectName("s5")
        self.calc = QtWidgets.QPushButton(fin3)
        self.calc.setGeometry(QtCore.QRect(300, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calc.setFont(font)
        self.calc.setObjectName("calc")
        self.back = QtWidgets.QPushButton(fin3)
        self.back.setGeometry(QtCore.QRect(50, 320, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.label_13 = QtWidgets.QLabel(fin3)
        self.label_13.setGeometry(QtCore.QRect(390, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.total = QtWidgets.QLineEdit(fin3)
        self.total.setEnabled(False)
        self.total.setGeometry(QtCore.QRect(560, 80, 121, 20))
        self.total.setText("")
        self.total.setAlignment(QtCore.Qt.AlignCenter)
        self.total.setObjectName("total")

        self.retranslateUi(fin3)
        QtCore.QMetaObject.connectSlotsByName(fin3)

    def retranslateUi(self, fin3):
        _translate = QtCore.QCoreApplication.translate
        fin3.setWindowTitle(_translate("fin3", "Розрахунок 3.Результат"))
        self.label.setText(_translate("fin3", "Результат моделювання вибору мігрантів між державами "))
        self.label_7.setText(_translate("fin3", "Загальна кі-сть мігрантів:"))
        self.tomenu.setText(_translate("fin3", "В меню"))
        self.label_8.setText(_translate("fin3", "Усього обрали Державу 1:"))
        self.label_9.setText(_translate("fin3", "Усього обрали Державу 2:"))
        self.label_10.setText(_translate("fin3", "Усього обрали Державу 3:"))
        self.label_11.setText(_translate("fin3", "Усього обрали Державу 4:"))
        self.label_12.setText(_translate("fin3", "Усього обрали Державу 5:"))
        self.calc.setText(_translate("fin3", "Обчислити"))
        self.back.setText(_translate("fin3", "Назад"))
        self.label_13.setText(_translate("fin3", "Кількість населення:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fin3 = QtWidgets.QDialog()
    ui = Ui_fin3()
    ui.setupUi(fin3)
    fin3.show()
    sys.exit(app.exec_())

