# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kkwin2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kkwin2(object):
    def setupUi(self, kkwin2):
        kkwin2.setObjectName("kkwin2")
        kkwin2.setEnabled(True)
        kkwin2.resize(720, 347)
        kkwin2.setMinimumSize(QtCore.QSize(720, 347))
        kkwin2.setMaximumSize(QtCore.QSize(720, 347))
        kkwin2.setStyleSheet("background-color:rgb(241,222,255);")
        self.label = QtWidgets.QLabel(kkwin2)
        self.label.setGeometry(QtCore.QRect(30, 10, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pot = QtWidgets.QLineEdit(kkwin2)
        self.pot.setEnabled(True)
        self.pot.setGeometry(QtCore.QRect(390, 120, 121, 20))
        self.pot.setText("")
        self.pot.setAlignment(QtCore.Qt.AlignCenter)
        self.pot.setObjectName("pot")
        self.back = QtWidgets.QPushButton(kkwin2)
        self.back.setGeometry(QtCore.QRect(560, 120, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.label_10 = QtWidgets.QLabel(kkwin2)
        self.label_10.setGeometry(QtCore.QRect(40, 180, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(kkwin2)
        self.label_11.setGeometry(QtCore.QRect(10, 220, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.total = QtWidgets.QLineEdit(kkwin2)
        self.total.setEnabled(True)
        self.total.setGeometry(QtCore.QRect(390, 180, 121, 20))
        self.total.setText("")
        self.total.setAlignment(QtCore.Qt.AlignCenter)
        self.total.setObjectName("total")
        self.born = QtWidgets.QLineEdit(kkwin2)
        self.born.setEnabled(True)
        self.born.setGeometry(QtCore.QRect(390, 250, 121, 20))
        self.born.setText("")
        self.born.setAlignment(QtCore.Qt.AlignCenter)
        self.born.setObjectName("born")
        self.next = QtWidgets.QPushButton(kkwin2)
        self.next.setGeometry(QtCore.QRect(560, 230, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.next.setFont(font)
        self.next.setObjectName("next")
        self.label_12 = QtWidgets.QLabel(kkwin2)
        self.label_12.setGeometry(QtCore.QRect(10, 90, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(kkwin2)
        self.label_13.setGeometry(QtCore.QRect(100, 120, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(kkwin2)
        self.label_2.setGeometry(QtCore.QRect(150, 250, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_14 = QtWidgets.QLabel(kkwin2)
        self.label_14.setGeometry(QtCore.QRect(170, 300, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.years = QtWidgets.QLineEdit(kkwin2)
        self.years.setEnabled(True)
        self.years.setGeometry(QtCore.QRect(390, 300, 121, 20))
        self.years.setText("")
        self.years.setAlignment(QtCore.Qt.AlignCenter)
        self.years.setObjectName("years")

        self.retranslateUi(kkwin2)
        QtCore.QMetaObject.connectSlotsByName(kkwin2)

    def retranslateUi(self, kkwin2):
        _translate = QtCore.QCoreApplication.translate
        kkwin2.setWindowTitle(_translate("kkwin2", "Розрахунок2.Вхідні дані"))
        self.label.setText(_translate("kkwin2", "Розрахунок 2. Моделювання вибору мігрантів між державами "))
        self.back.setText(_translate("kkwin2", "Назад"))
        self.label_10.setText(_translate("kkwin2", "Загальна кі-сть економічно активного населення:"))
        self.label_11.setText(_translate("kkwin2", "Відсоток народжуваності  (десятковим дробом) серед "))
        self.next.setText(_translate("kkwin2", "Вперед"))
        self.label_12.setText(_translate("kkwin2", "Відсоток (десятковим дробом) потенційних мігрантів"))
        self.label_13.setText(_translate("kkwin2", "серед економічно активного населення:"))
        self.label_2.setText(_translate("kkwin2", "економічно активного населення:"))
        self.label_14.setText(_translate("kkwin2", "Кількість років для розрахунку:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kkwin2 = QtWidgets.QDialog()
    ui = Ui_kkwin2()
    ui.setupUi(kkwin2)
    kkwin2.show()
    sys.exit(app.exec_())

