# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kkwin1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_kkwin1(object):
    def setupUi(self, kkwin1):
        kkwin1.setObjectName("kkwin1")
        kkwin1.setEnabled(True)
        kkwin1.resize(720, 480)
        kkwin1.setMinimumSize(QtCore.QSize(720, 480))
        kkwin1.setMaximumSize(QtCore.QSize(720, 480))
        kkwin1.setStyleSheet("background-color:rgb(241,222,255);")
        self.label = QtWidgets.QLabel(kkwin1)
        self.label.setGeometry(QtCore.QRect(190, 10, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(kkwin1)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(kkwin1)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(kkwin1)
        self.label_4.setGeometry(QtCore.QRect(40, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(kkwin1)
        self.label_5.setGeometry(QtCore.QRect(40, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(kkwin1)
        self.label_6.setGeometry(QtCore.QRect(40, 430, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(kkwin1)
        self.label_7.setGeometry(QtCore.QRect(110, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(kkwin1)
        self.label_8.setGeometry(QtCore.QRect(180, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(kkwin1)
        self.label_9.setGeometry(QtCore.QRect(250, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(kkwin1)
        self.label_10.setGeometry(QtCore.QRect(320, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(kkwin1)
        self.label_11.setGeometry(QtCore.QRect(390, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(100, 160, 41, 20))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.k1k2 = QtWidgets.QLineEdit(kkwin1)
        self.k1k2.setEnabled(True)
        self.k1k2.setGeometry(QtCore.QRect(170, 160, 41, 20))
        self.k1k2.setAlignment(QtCore.Qt.AlignCenter)
        self.k1k2.setObjectName("k1k2")
        self.k1k3 = QtWidgets.QLineEdit(kkwin1)
        self.k1k3.setEnabled(True)
        self.k1k3.setGeometry(QtCore.QRect(240, 160, 41, 20))
        self.k1k3.setAlignment(QtCore.Qt.AlignCenter)
        self.k1k3.setObjectName("k1k3")
        self.k1k4 = QtWidgets.QLineEdit(kkwin1)
        self.k1k4.setEnabled(True)
        self.k1k4.setGeometry(QtCore.QRect(310, 160, 41, 20))
        self.k1k4.setAlignment(QtCore.Qt.AlignCenter)
        self.k1k4.setObjectName("k1k4")
        self.k1k5 = QtWidgets.QLineEdit(kkwin1)
        self.k1k5.setEnabled(True)
        self.k1k5.setGeometry(QtCore.QRect(380, 160, 41, 20))
        self.k1k5.setAlignment(QtCore.Qt.AlignCenter)
        self.k1k5.setObjectName("k1k5")
        self.lineEdit_6 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 230, 41, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 230, 41, 20))
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.k2k3 = QtWidgets.QLineEdit(kkwin1)
        self.k2k3.setEnabled(True)
        self.k2k3.setGeometry(QtCore.QRect(240, 230, 41, 20))
        self.k2k3.setAlignment(QtCore.Qt.AlignCenter)
        self.k2k3.setObjectName("k2k3")
        self.k2k4 = QtWidgets.QLineEdit(kkwin1)
        self.k2k4.setEnabled(True)
        self.k2k4.setGeometry(QtCore.QRect(310, 230, 41, 20))
        self.k2k4.setAlignment(QtCore.Qt.AlignCenter)
        self.k2k4.setObjectName("k2k4")
        self.k2k5 = QtWidgets.QLineEdit(kkwin1)
        self.k2k5.setEnabled(True)
        self.k2k5.setGeometry(QtCore.QRect(380, 230, 41, 20))
        self.k2k5.setAlignment(QtCore.Qt.AlignCenter)
        self.k2k5.setObjectName("k2k5")
        self.lineEdit_11 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_11.setEnabled(False)
        self.lineEdit_11.setGeometry(QtCore.QRect(100, 300, 41, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setGeometry(QtCore.QRect(170, 300, 41, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setGeometry(QtCore.QRect(240, 300, 41, 20))
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.k3k4 = QtWidgets.QLineEdit(kkwin1)
        self.k3k4.setEnabled(True)
        self.k3k4.setGeometry(QtCore.QRect(310, 300, 41, 20))
        self.k3k4.setAlignment(QtCore.Qt.AlignCenter)
        self.k3k4.setObjectName("k3k4")
        self.k3k5 = QtWidgets.QLineEdit(kkwin1)
        self.k3k5.setEnabled(True)
        self.k3k5.setGeometry(QtCore.QRect(380, 300, 41, 20))
        self.k3k5.setAlignment(QtCore.Qt.AlignCenter)
        self.k3k5.setObjectName("k3k5")
        self.lineEdit_16 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setGeometry(QtCore.QRect(100, 370, 41, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_17.setEnabled(False)
        self.lineEdit_17.setGeometry(QtCore.QRect(170, 370, 41, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_18.setEnabled(False)
        self.lineEdit_18.setGeometry(QtCore.QRect(240, 370, 41, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setGeometry(QtCore.QRect(310, 370, 41, 21))
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.k4k5 = QtWidgets.QLineEdit(kkwin1)
        self.k4k5.setEnabled(True)
        self.k4k5.setGeometry(QtCore.QRect(380, 370, 41, 20))
        self.k4k5.setAlignment(QtCore.Qt.AlignCenter)
        self.k4k5.setObjectName("k4k5")
        self.lineEdit_21 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_21.setEnabled(False)
        self.lineEdit_21.setGeometry(QtCore.QRect(100, 430, 41, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_22.setEnabled(False)
        self.lineEdit_22.setGeometry(QtCore.QRect(170, 430, 41, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_23.setEnabled(False)
        self.lineEdit_23.setGeometry(QtCore.QRect(240, 430, 41, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_24.setEnabled(False)
        self.lineEdit_24.setGeometry(QtCore.QRect(310, 430, 41, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(kkwin1)
        self.lineEdit_25.setEnabled(False)
        self.lineEdit_25.setGeometry(QtCore.QRect(380, 430, 41, 20))
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.back = QtWidgets.QPushButton(kkwin1)
        self.back.setGeometry(QtCore.QRect(510, 180, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.next = QtWidgets.QPushButton(kkwin1)
        self.next.setGeometry(QtCore.QRect(510, 310, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.next.setFont(font)
        self.next.setObjectName("next")

        self.retranslateUi(kkwin1)
        QtCore.QMetaObject.connectSlotsByName(kkwin1)

    def retranslateUi(self, kkwin1):
        _translate = QtCore.QCoreApplication.translate
        kkwin1.setWindowTitle(_translate("kkwin1", "Розрахунок1.Критерії"))
        self.label.setText(_translate("kkwin1", "Матриця попарних порівнянь Критеріїв"))
        self.label_2.setText(_translate("kkwin1", "К1"))
        self.label_3.setText(_translate("kkwin1", "К2"))
        self.label_4.setText(_translate("kkwin1", "К3"))
        self.label_5.setText(_translate("kkwin1", "К4"))
        self.label_6.setText(_translate("kkwin1", "К5"))
        self.label_7.setText(_translate("kkwin1", "К1"))
        self.label_8.setText(_translate("kkwin1", "К2"))
        self.label_9.setText(_translate("kkwin1", "К3"))
        self.label_10.setText(_translate("kkwin1", "К4"))
        self.label_11.setText(_translate("kkwin1", "К5"))
        self.lineEdit.setText(_translate("kkwin1", "1"))
        self.lineEdit_7.setText(_translate("kkwin1", "1"))
        self.lineEdit_13.setText(_translate("kkwin1", "1"))
        self.lineEdit_19.setText(_translate("kkwin1", "1"))
        self.lineEdit_25.setText(_translate("kkwin1", "1"))
        self.back.setText(_translate("kkwin1", "Назад"))
        self.next.setText(_translate("kkwin1", "Далі"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kkwin1 = QtWidgets.QDialog()
    ui = Ui_kkwin1()
    ui.setupUi(kkwin1)
    kkwin1.show()
    sys.exit(app.exec_())

